/*******************************************************************************
 * AbyssalCraft
 * Copyright (c) 2012 - 2025 Shinoow.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser Public License v3
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Contributors:
 *     Shinoow -  implementation
 ******************************************************************************/
package com.shinoow.abyssalcraft.data;

import java.util.HashMap;
import java.util.Map;

import com.shinoow.abyssalcraft.api.item.ACItems;

import net.minecraft.world.item.Item;
import net.minecraftforge.registries.RegistryObject;

/**
 * Maps each item to the texture file it uses.
 * <p>
 * The 1.12.2 assets are abbreviated ({@code ai.png} for the abyssalnite ingot) and the port uses
 * descriptive registry names, so a generated item model cannot infer its texture. The textures are
 * All Rights Reserved and are left untouched, so the mapping lives here instead of renaming files.
 * <p>
 * Generated by {@code plans/.../derive_item_texture_mapping.py}, which read the layer0 texture out
 * of each 1.12.2 item model, so every entry is the texture that item actually had.
 * <p>
 * Items that were metadata variants on 1.12.2 (charms, essences, skins, scrolls, shoggoth flesh)
 * are absent: each needs one model per former variant, which lands with those items themselves.
 */
final class ACItemTextures {

    /** Texture base name per item, relative to {@code textures/items/}. */
    /** Texture base name per item, relative to {@code textures/items/}. */
    static final Map<RegistryObject<Item>, String> ALL = buildTextureMap();

    /**
     * Built imperatively rather than with {@code Map.ofEntries}: there are far more entries
     * than that method's fixed-arity overloads accept.
     */
    private static Map<RegistryObject<Item>, String> buildTextureMap() {
        Map<RegistryObject<Item>, String> textures = new HashMap<>();
        textures.put(ACItems.abyssalnite_axe, "aa");
        textures.put(ACItems.abyssalnite_boots, "aab");
        textures.put(ACItems.abyssalnite_chestplate, "aac");
        textures.put(ACItems.abyssalnite_helmet, "aah");
        textures.put(ACItems.abyssalnite_hoe, "ah");
        textures.put(ACItems.abyssalnite_ingot, "ai");
        textures.put(ACItems.abyssalnite_leggings, "aap");
        textures.put(ACItems.abyssalnite_pickaxe, "ap");
        textures.put(ACItems.abyssalnite_shovel, "as");
        textures.put(ACItems.abyssalnite_sword, "asw");
        textures.put(ACItems.abyssalnite_upgrade_kit, "abyu");
        textures.put(ACItems.azathoth_charm, "charm_azathoth");
        textures.put(ACItems.azathoth_engraved_coin, "azathothcoin");
        textures.put(ACItems.azathoth_engraving, "engraving_azathoth");
        textures.put(ACItems.beef_on_a_plate, "beep");
        textures.put(ACItems.blank_engraving, "engraving_blank");
        textures.put(ACItems.carbon_cluster, "carbc");
        textures.put(ACItems.chicken_on_a_plate, "chip");
        textures.put(ACItems.chunk_of_abyssalnite, "ac");
        textures.put(ACItems.chunk_of_coralium, "cc");
        textures.put(ACItems.cobblestone_upgrade_kit, "cobu");
        textures.put(ACItems.coin, "coin");
        textures.put(ACItems.copper_ingot, "ic");
        textures.put(ACItems.coralium_brick, "cbrick");
        textures.put(ACItems.coralium_gem, "cg");
        textures.put(ACItems.coralium_plagued_flesh, "cf");
        textures.put(ACItems.coralium_plate, "cpp");
        textures.put(ACItems.coralium_upgrade_kit, "coru");
        textures.put(ACItems.crystal_fragment, "crystalfragment");
        textures.put(ACItems.crystal_shard, "crystalshard");
        textures.put(ACItems.cthulhu_charm, "charm_cthulhu");
        textures.put(ACItems.cthulhu_engraved_coin, "cthulhucoin");
        textures.put(ACItems.cthulhu_engraving, "engraving_cthulhu");
        textures.put(ACItems.darkstone_axe, "da");
        textures.put(ACItems.darkstone_hoe, "dh");
        textures.put(ACItems.darkstone_pickaxe, "dp");
        textures.put(ACItems.darkstone_shovel, "ds");
        textures.put(ACItems.darkstone_sword, "dsw");
        textures.put(ACItems.dense_carbon_cluster, "dcarbc");
        textures.put(ACItems.depths_boots, "adb");
        textures.put(ACItems.depths_chestplate, "adc");
        textures.put(ACItems.depths_helmet, "adh");
        textures.put(ACItems.depths_leggings, "adp");
        textures.put(ACItems.diamond_upgrade_kit, "diau");
        textures.put(ACItems.dirty_plate, "dirtyplate");
        textures.put(ACItems.dread_cloth, "dc");
        textures.put(ACItems.dread_fragment, "df");
        textures.put(ACItems.dreaded_abyssalnite_boots, "adab");
        textures.put(ACItems.dreaded_abyssalnite_chestplate, "adac");
        textures.put(ACItems.dreaded_abyssalnite_helmet, "adah");
        textures.put(ACItems.dreaded_abyssalnite_leggings, "adap");
        textures.put(ACItems.dreaded_chunk_of_abyssalnite, "dac");
        textures.put(ACItems.dreaded_shard_of_abyssalnite, "dsoa");
        textures.put(ACItems.dreadium_axe, "dda");
        textures.put(ACItems.dreadium_boots, "addb");
        textures.put(ACItems.dreadium_chestplate, "addc");
        textures.put(ACItems.dreadium_helmet, "addh");
        textures.put(ACItems.dreadium_hoe, "ddh");
        textures.put(ACItems.dreadium_ingot, "di");
        textures.put(ACItems.dreadium_leggings, "addp");
        textures.put(ACItems.dreadium_pickaxe, "ddp");
        textures.put(ACItems.dreadium_plate, "dpp");
        textures.put(ACItems.dreadium_samurai_boots, "adsb");
        textures.put(ACItems.dreadium_samurai_chestplate, "adsc");
        textures.put(ACItems.dreadium_samurai_helmet, "adsh");
        textures.put(ACItems.dreadium_samurai_leggings, "adsp");
        textures.put(ACItems.dreadium_shovel, "dds");
        textures.put(ACItems.dreadium_sword, "ddsw");
        textures.put(ACItems.dreadium_upgrade_kit, "dreu");
        textures.put(ACItems.elder_engraved_coin, "eldercoin");
        textures.put(ACItems.elder_engraving, "engraving_elder");
        textures.put(ACItems.eldritch_scale, "eldritchscale");
        textures.put(ACItems.essence_of_the_gatekeeper, "gatekeeperessence");
        textures.put(ACItems.ethaxium_axe, "ea");
        textures.put(ACItems.ethaxium_boots, "aeb");
        textures.put(ACItems.ethaxium_brick, "eb");
        textures.put(ACItems.ethaxium_chestplate, "aec");
        textures.put(ACItems.ethaxium_helmet, "aeh");
        textures.put(ACItems.ethaxium_hoe, "eh");
        textures.put(ACItems.ethaxium_ingot, "ei");
        textures.put(ACItems.ethaxium_leggings, "aep");
        textures.put(ACItems.ethaxium_pickaxe, "ep");
        textures.put(ACItems.ethaxium_shovel, "es");
        textures.put(ACItems.ethaxium_sword, "esw");
        textures.put(ACItems.ethaxium_upgrade_kit, "ethu");
        textures.put(ACItems.eye_of_the_abyss, "eoa");
        textures.put(ACItems.fish_on_a_plate, "fisp");
        textures.put(ACItems.fried_egg, "friedegg");
        textures.put(ACItems.fried_egg_on_a_plate, "eggp");
        textures.put(ACItems.gold_upgrade_kit, "golu");
        textures.put(ACItems.hastur_charm, "charm_hastur");
        textures.put(ACItems.hastur_engraved_coin, "hasturcoin");
        textures.put(ACItems.hastur_engraving, "engraving_hastur");
        textures.put(ACItems.iron_plate, "plate");
        textures.put(ACItems.iron_upgrade_kit, "irou");
        textures.put(ACItems.jzahar_charm, "charm_jzahar");
        textures.put(ACItems.jzahar_engraved_coin, "jzaharcoin");
        textures.put(ACItems.jzahar_engraving, "engraving_jzahar");
        textures.put(ACItems.life_crystal, "lifecrystal");
        textures.put(ACItems.methane, "methane");
        textures.put(ACItems.mre, "mre");
        textures.put(ACItems.nitre, "nitre");
        textures.put(ACItems.nyarlathotep_charm, "charm_nyarlathotep");
        textures.put(ACItems.nyarlathotep_engraved_coin, "nyarlathotepcoin");
        textures.put(ACItems.nyarlathotep_engraving, "engraving_nyarlathotep");
        textures.put(ACItems.oblivion_catalyst, "oc");
        textures.put(ACItems.omothol_flesh, "omotholflesh");
        textures.put(ACItems.plated_coralium_boots, "acbp");
        textures.put(ACItems.plated_coralium_chestplate, "accp");
        textures.put(ACItems.plated_coralium_helmet, "achp");
        textures.put(ACItems.plated_coralium_leggings, "acpp");
        textures.put(ACItems.pork_on_a_plate, "porp");
        textures.put(ACItems.powerstone_tracker, "psdlf");
        textures.put(ACItems.refined_coralium_axe, "rca");
        textures.put(ACItems.refined_coralium_boots, "acb");
        textures.put(ACItems.refined_coralium_chestplate, "acc");
        textures.put(ACItems.refined_coralium_helmet, "ach");
        textures.put(ACItems.refined_coralium_hoe, "rch");
        textures.put(ACItems.refined_coralium_ingot, "rci");
        textures.put(ACItems.refined_coralium_leggings, "acp");
        textures.put(ACItems.refined_coralium_pickaxe, "rcp");
        textures.put(ACItems.refined_coralium_shovel, "rcs");
        textures.put(ACItems.refined_coralium_sword, "rcsw");
        textures.put(ACItems.shadow_fragment, "sf");
        textures.put(ACItems.shadow_gem, "sg");
        textures.put(ACItems.shadow_shard, "ss");
        textures.put(ACItems.shard_of_oblivion, "os");
        textures.put(ACItems.shub_niggurath_charm, "charm_shubniggurath");
        textures.put(ACItems.shub_niggurath_engraved_coin, "shubniggurathcoin");
        textures.put(ACItems.shub_niggurath_engraving, "engraving_shubniggurath");
        textures.put(ACItems.sulfur, "sulfur");
        textures.put(ACItems.tin_ingot, "it");
        textures.put(ACItems.transmutation_gem, "transmutationgem");
        textures.put(ACItems.washcloth, "cloth");
        textures.put(ACItems.yog_sothoth_charm, "charm_yogsothoth");
        textures.put(ACItems.yog_sothoth_engraved_coin, "yogsothothcoin");
        textures.put(ACItems.yog_sothoth_engraving, "engraving_yogsothoth");
        // Crystals and shards all share one greyscale sprite and are tinted per type at render
        // time, exactly as on 1.12.2, so every type maps to the same texture.
        ACItems.crystals.forEach(entry -> textures.put(entry, "crystal"));
        ACItems.crystal_shards.forEach(entry -> textures.put(entry, "crystalshard"));

        // The nugget was a metadata item on 1.12.2 with one sprite per metal; the abyssalnite one
        // stands in until those variants are split into separate items.
        textures.put(ACItems.ingot_nugget, "nugget_abyssalnite");
        // Items whose 1.12.2 model file was absent or held metadata variants. Each texture below
        // was confirmed present; the variant items themselves are split in a later phase, so these
        // point at the base sprite for now.
        textures.put(ACItems.coralium_pearl, "cp");
        textures.put(ACItems.ritual_charm, "charm");
        textures.put(ACItems.skin, "skin_abyssalwasteland");
        textures.put(ACItems.essence, "essence_abyssalwasteland");
        textures.put(ACItems.shoggoth_flesh, "shoggothflesh_overworld");
        textures.put(ACItems.configurator_shard, "configurator/configurator_shard_0");
        textures.put(ACItems.scroll, "scrolls/scroll_basic");
        textures.put(ACItems.unique_scroll, "scrolls/scroll_unique_anti");
        textures.put(ACItems.antidote, "coralium_antidote");
        textures.put(ACItems.small_crystal_bag, "crystalbag_small");
        textures.put(ACItems.medium_crystal_bag, "crystalbag_medium");
        textures.put(ACItems.large_crystal_bag, "crystalbag_large");
        textures.put(ACItems.huge_crystal_bag, "crystalbag_huge");
        return Map.copyOf(textures);
    }

    private ACItemTextures() {}
}
